node app.js MainInfo parsed/MainInfo
node app.js Patchnotes parsed/Patchnotes
node app.js Localization parsed/Localization
node app.js Dialogues parsed/Dialogues
node app.js InstallationAndConfigs parsed/InstallationAndConfigs
node app.js TerritorySystem parsed/TerritorySystem
node app.js Transmog parsed/Transmog
node app.js Quests parsed/Quests
node app.js QuestsEvents parsed/QuestsEvents
node app.js Trader parsed/Trader
node app.js Marketplace parsed/Marketplace
node app.js Teleporter parsed/Teleporter
node app.js ServerInfo parsed/ServerInfo
node app.js Banker parsed/Banker
node app.js Gambler parsed/Gambler
node app.js Buffer parsed/Buffer
node app.js NPC parsed/NPC